name: task
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Flutter library to load and cache network images. Can also be used with placeholder and
  # error widgets.
  cached_network_image: ^3.2.3

  # A powerful HTTP networking package for Dart/Flutter, supports Global configuration, Interceptors, FormData,
  # Request cancellation, File uploading/downloading, Timeout, Custom adapters, Transformers, etc.
  dio: ^5.3.2

  # Flutter widgets that make it easy to implement the BLoC design pattern.
  flutter_bloc: ^8.1.3

  # Simple direct Service Locator that allows to decouple the interface from a concrete
  # implementation and to access the concrete implementation from everywhere in your App
  get_it: ^7.6.4

  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0

  # An extremely easy-to-use method call debouncer and throttler package for Dart/Flutter.
  easy_debounce: ^2.0.3

  # For loading and refreshing data (used for pagination)
  pull_to_refresh: ^2.0.0

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable
  # Vector Graphics 1.1 files.
  flutter_svg: ^2.0.2

  # Functional Programming in Dart. Purify your Dart code using efficient immutable data structures,
  # monads, lenses and other FP tools.
  dartz: ^0.10.1

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5

  # A pure Dart library that checks for internet by opening a socket to a list of
  # specified addresses, each with individual port and timeout. Defaults are provided for convenience
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/noimage.jpg


